name: 'Releaser'
description: 'Trigger travis or GH action via comment or label'
inputs:
  gh-bot-token:  # id of input
    description: 'Token to use to comment on PR'
    required: true
  gh-release-bot-token:
    description: 'Token to use to trigger a build/release'
    required: false
    default: false
  travis-config:
    description: 'JSON of travis config: script, group?, repo?, token?'
    required: false
    default: '{}'
  gh-config:
    description: 'JSON of github action config: script, group?, repo?, token?'
    required: false
    default: '{}'
  allowed-users:
    description: 'Array of users who can trigger a release'
    required: false
    default: '[]'
runs:
  using: 'node16'
  main: 'dist/index.js'
