on:
  pull_request:
    types: [ labeled, closed ]
  issue_comment:
    types: [ created, edited ]

jobs:
  pr_merged:
    runs-on: ubuntu-latest
    name: Trigger job on comment, merge or label
    steps:
      - name: Trigger release
        id: release
        uses: karelhala/gh-actions-test@v1.32
        with:
          gh-bot-token: ${{ secrets.GH_BOT_TOKEN }}
          travis-config: '{"token":"${{ secrets.TRAVIS_TOKEN }}"}'
          allowed-users: '["karelhala"]'
