on:
  pull_request:
    types: [ labeled ]
  issue_comment:
    types: [created, edited]

jobs:
  pr_labeled:
    runs-on: ubuntu-latest
    name: A job to trigger released on label
    if: ${{ github.event.label.name == 'release' || github.event.label.name == 'release minor' }}
    steps:
      - name: Hello world action step
        id: hello
        uses: karelhala/gh-actions-test@v1.2
        with:
          gh-bot-token: ${{ secrets.GH_BOT_TOKEN }}
  pr_commented_bug:
    runs-on: ubuntu-latest
    name: A job to trigger released on comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'release' }}
    steps:
      - name: Hello world action step
        id: hello
        uses: karelhala/gh-actions-test@v1.2
        with:
          gh-bot-token: ${{ secrets.GH_BOT_TOKEN }}
          release-type: 'bug'
  pr_commented_minor:
    runs-on: ubuntu-latest
    name: A job to trigger released on comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'release minor' }}
    steps:
      - name: Hello world action step
        id: hello
        uses: karelhala/gh-actions-test@v1.2
        with:
          gh-bot-token: ${{ secrets.GH_BOT_TOKEN }}
          release-type: 'minor'
  pr_commented_major:
    runs-on: ubuntu-latest
    name: A job to trigger released on comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'release major' }}
    steps:
      - name: Hello world action step
        id: hello
        uses: karelhala/gh-actions-test@v1.2
        with:
          gh-bot-token: ${{ secrets.GH_BOT_TOKEN }}
          release-type: 'major'
