on:
  pull_request:
    types: [ labeled ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    if: ${{ github.event.label.name == 'bug' }}
    steps:
      - name: Hello world action step
        id: hello
        uses: karelhala/gh-actions-test@v1.1
        with:
          gh-bot-token: ${{ secrets.GH_BOT_TOKEN }}
